
package GameFrame;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.*;

/**
 *
 * @author Whisper73
 */
public class JFrameGame extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGame
     */
    public ArrayList<javax.swing.JTextField> tablero;   
    ConexionApp conectar;
    GestionDeGanador gg;
    int xMouse , yMouse;
    public JFrameGame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tablero = new ArrayList<>();
        this.conectar = new ConexionApp();
        this.gg = new GestionDeGanador(); 
        GestionDeGanador.setGanadorExiste();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        player1 = new javax.swing.JPanel();
        labelp1 = new javax.swing.JLabel();
        player2 = new javax.swing.JPanel();
        labelp2 = new javax.swing.JLabel();
        difficult = new javax.swing.JComboBox<>();
        restart = new javax.swing.JPanel();
        labelrt = new javax.swing.JLabel();
        planel00 = new javax.swing.JTextField();
        panel01 = new javax.swing.JTextField();
        panel02 = new javax.swing.JTextField();
        panel10 = new javax.swing.JTextField();
        panel11 = new javax.swing.JTextField();
        panel12 = new javax.swing.JTextField();
        panel20 = new javax.swing.JTextField();
        panel21 = new javax.swing.JTextField();
        panel22 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField7.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 380));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(96, 77, 170));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        panelSuperior.setBackground(new java.awt.Color(153, 60, 247));
        panelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelSuperiorMouseDragged(evt);
            }
        });
        panelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSuperiorMousePressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        exit.setText("X  ");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tic - Tac - Toe");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23))
        );

        player1.setBackground(new java.awt.Color(255, 109, 121));
        player1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));

        labelp1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        labelp1.setForeground(new java.awt.Color(255, 255, 255));
        labelp1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelp1.setText("Player 1 X");

        javax.swing.GroupLayout player1Layout = new javax.swing.GroupLayout(player1);
        player1.setLayout(player1Layout);
        player1Layout.setHorizontalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelp1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        player1Layout.setVerticalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        player2.setBackground(new java.awt.Color(109, 120, 232));
        player2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        labelp2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        labelp2.setForeground(new java.awt.Color(255, 255, 255));
        labelp2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelp2.setText("Player 2 O");

        javax.swing.GroupLayout player2Layout = new javax.swing.GroupLayout(player2);
        player2.setLayout(player2Layout);
        player2Layout.setHorizontalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelp2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        player2Layout.setVerticalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelp2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        difficult.setBackground(new java.awt.Color(70, 253, 177));
        difficult.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        difficult.setForeground(new java.awt.Color(51, 51, 51));
        difficult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P1 vs P2", "P1 vs Machine" }));
        difficult.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        difficult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        restart.setBackground(new java.awt.Color(109, 188, 233));
        restart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        restart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restartMouseExited(evt);
            }
        });

        labelrt.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        labelrt.setForeground(new java.awt.Color(255, 255, 255));
        labelrt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelrt.setText("Restart!");

        javax.swing.GroupLayout restartLayout = new javax.swing.GroupLayout(restart);
        restart.setLayout(restartLayout);
        restartLayout.setHorizontalGroup(
            restartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restartLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelrt)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        restartLayout.setVerticalGroup(
            restartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelrt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        planel00.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        planel00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        planel00.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        planel00.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        planel00.setFocusable(false);
        planel00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                planel00MouseClicked(evt);
            }
        });

        panel01.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        panel01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel01.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        panel01.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        panel01.setFocusable(false);
        panel01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel01MouseClicked(evt);
            }
        });

        panel02.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        panel02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel02.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        panel02.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        panel02.setFocusable(false);
        panel02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel02MouseClicked(evt);
            }
        });

        panel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        panel10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 204)));
        panel10.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        panel10.setFocusable(false);
        panel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel10MouseClicked(evt);
            }
        });

        panel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        panel11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 0)));
        panel11.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        panel11.setFocusable(false);
        panel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel11MouseClicked(evt);
            }
        });

        panel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        panel12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        panel12.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        panel12.setFocusable(false);
        panel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel12MouseClicked(evt);
            }
        });

        panel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        panel20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        panel20.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        panel20.setFocusable(false);
        panel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel20MouseClicked(evt);
            }
        });

        panel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        panel21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 0)));
        panel21.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        panel21.setFocusable(false);
        panel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel21MouseClicked(evt);
            }
        });

        panel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        panel22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        panel22.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        panel22.setFocusable(false);
        panel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel22MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Difficult!");

        jLabel2.setText("Power by Java © Whisper73-2023 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(difficult, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(planel00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(panel02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(panel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(panel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(planel00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panel01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panel02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(panel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(difficult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelSuperiorMousePressed

    private void panelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_panelSuperiorMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setForeground(new java.awt.Color(255,109,121));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_exitMouseExited

    private void planel00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planel00MouseClicked
        accionar(this.planel00,0);
    }//GEN-LAST:event_planel00MouseClicked

    private void panel01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel01MouseClicked
        accionar(this.panel01,1);
    }//GEN-LAST:event_panel01MouseClicked

    private void panel02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel02MouseClicked
        accionar(this.panel02,2);
    }//GEN-LAST:event_panel02MouseClicked

    private void panel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel10MouseClicked
        accionar(this.panel10,3);
    }//GEN-LAST:event_panel10MouseClicked

    private void panel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel11MouseClicked
         accionar(this.panel11,4);

    }//GEN-LAST:event_panel11MouseClicked

    private void panel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel12MouseClicked
        accionar(this.panel12,5);
    }//GEN-LAST:event_panel12MouseClicked

    private void panel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel20MouseClicked
         accionar(this.panel20,6);
    }//GEN-LAST:event_panel20MouseClicked

    private void panel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel21MouseClicked
         accionar(this.panel21,7);
    }//GEN-LAST:event_panel21MouseClicked

    private void panel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel22MouseClicked
         accionar(this.panel22,8);
    }//GEN-LAST:event_panel22MouseClicked

    private void restartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseClicked

        this.ReiniciarJuego();
    }//GEN-LAST:event_restartMouseClicked

    private void restartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseEntered
       restart.setBackground(new java.awt.Color(255,109,121));
         
    }//GEN-LAST:event_restartMouseEntered

    private void restartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseExited
        restart.setBackground(new java.awt.Color(109,188,233));
    }//GEN-LAST:event_restartMouseExited
    

    private void accionar(javax.swing.JTextField p, int pos) {

        if (!gg.isGanadorExiste()) {
            this.tablero.add(p);
            if ("".equals(p.getText()) && this.difficult.getSelectedIndex() == 0) {
                switch (this.conectar.Jugar(pos)) {
                    case 1 ->
                        p.setText("X");
                    case 2 ->
                        p.setText("O");
                    default ->
                        JOptionPane.showMessageDialog(null, "Ups, Algo Salio mal");
                }

            } else if ("".equals(p.getText()) && this.difficult.getSelectedIndex() == 1) {
                if (!GestionDeGanador.ganadorExiste) {
                     p.setText("X");
                    this.conectar.JugarVsMachine(pos);
                    AsignarPosicion(this.conectar.MachineConector());
                }else{
                    this.ReiniciarJuego();
                }
               
            }

        } else {
            this.ReiniciarJuego();
        }

        if (this.conectar.turno.getNumTurnos() == 9 && !GestionDeGanador.ganadorExiste) {
            JOptionPane.showMessageDialog(null, " XO Empate !! ");
            this.ReiniciarJuego();
        }

    }

    private void AsignarPosicion(int posO) {

        if (posO < 10) {
            switch (posO) {
                case 0 -> {
                    this.conectar.JugarVsMachine(0);
                    this.planel00.setText("O");
                    this.tablero.add(this.planel00);
                }
                case 1 -> {
                    this.conectar.JugarVsMachine(1);
                    this.panel01.setText("O");
                    this.tablero.add(this.panel01);
                }
                case 2 -> {
                    this.conectar.JugarVsMachine(2);
                    this.panel02.setText("O");
                    this.tablero.add(this.panel02);
                }
                case 3 -> {
                    this.conectar.JugarVsMachine(3);
                    this.panel10.setText("O");
                    this.tablero.add(this.panel10);
                }
                case 4 -> {
                    this.conectar.JugarVsMachine(4);
                    this.panel11.setText("O");
                    this.tablero.add(this.panel11);
                }
                case 5 -> {
                    this.conectar.JugarVsMachine(5);
                    this.panel12.setText("O");
                    this.tablero.add(this.panel12);
                }
                case 6 -> {
                    this.conectar.JugarVsMachine(6);
                    this.panel20.setText("O");
                    this.tablero.add(this.panel20);
                }
                case 7 -> {
                    this.conectar.JugarVsMachine(7);
                    this.panel21.setText("O");
                    this.tablero.add(this.panel21);
                }
                case 8 -> {
                    this.conectar.JugarVsMachine(8);
                    this.panel22.setText("O");
                    this.tablero.add(this.panel22);
                }
                default ->
                    JOptionPane.showMessageDialog(null, "Ups, Algo Salio mal");
            }
           
        } else{
            JOptionPane.showMessageDialog(null, " XO Empate !! ");
            this.ReiniciarJuego();
        }
    }

    public void ReiniciarJuego() {
        conectar.BorrarTablero(this.tablero);
        this.tablero = new ArrayList<>();
        this.conectar = new ConexionApp();
        this.gg = new GestionDeGanador();
        GestionDeGanador.setGanadorExiste();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameGame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> difficult;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel labelp1;
    private javax.swing.JLabel labelp2;
    private javax.swing.JLabel labelrt;
    private javax.swing.JTextField panel01;
    private javax.swing.JTextField panel02;
    private javax.swing.JTextField panel10;
    private javax.swing.JTextField panel11;
    private javax.swing.JTextField panel12;
    private javax.swing.JTextField panel20;
    private javax.swing.JTextField panel21;
    private javax.swing.JTextField panel22;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextField planel00;
    private javax.swing.JPanel player1;
    private javax.swing.JPanel player2;
    private javax.swing.JPanel restart;
    // End of variables declaration//GEN-END:variables

}
